-- Migration 011: seed de descripción + color de las categorías de salestracker.
-- Datos exportados de la app Next original (tabla `categories`). Rellena
-- description/color por NOMBRE de las categorías ya importadas del hub (que llegan
-- solo con nombre). Idempotente y NO destructivo: el DO UPDATE solo actúa cuando
-- `description IS NULL` (categoría recién importada, sin tocar), de modo que las
-- ediciones que un admin haga luego NO se pisan en cada arranque.
INSERT INTO portal.st_categories AS c (name, description, color) VALUES
  ('Accesorios', 'Accesorios de todo tipo', '#3b82f6'),
  ('Accesorios Solar', 'Accesorios de SSFV', '#ef4444'),
  ('Alquileres', 'Aquiler de Equipos y Herramientas', '#3b82f6'),
  ('AP Series', 'Analizadores Horiba modelos AP Series', '#10b981'),
  ('Bios Defender', 'Medidores de Flujo Marca Mesalabs modelos Bios Defender', '#3B82F6'),
  ('Botellas Gases', 'Cilindros de Gases de Referencia y Calibración', '#0a7cf5'),
  ('CAL CO', 'Calibración de Analizadores de CO', '#ef4444'),
  ('CAL NOx', 'Calibración de Analizadores de NOx', '#8b5cf6'),
  ('CAL O3', 'Calibración de Analizadores de O3', '#f59e0b'),
  ('CAL PM', 'Calibración de Monitores de PM Grimm EDM180 / 280', '#10b981'),
  ('CAL SO2', 'Calibración de Analizadores de SO2', '#06b6d4'),
  ('CAL W', 'Calibración de Sensores / Sondas de Calidad del Agua', '#3B82F6'),
  ('Comisiones', 'Comisiones de Venta', '#f43f5e'),
  ('Consultoría', 'Consultoría', '#84cc16'),
  ('C&R APMA-370', 'C&R de analizadores Horiba APMA-370', '#06b6d4'),
  ('C&R APNA-370', 'C&R de analizadores Horiba APNA-370', '#84cc16'),
  ('C&R APNA-370 NH3', 'C&R de analizadores Horiba APNA-370 NH3', '#f73b8c'),
  ('C&R APOA-370', 'C&R de analizadores Horiba APOA-370', '#f91515'),
  ('C&R APSA-370', 'C&R de analizadores Horiba APSA-370', '#6366f1'),
  ('C&R APSA-370 H2S', 'C&R de analizadores Horiba APSA-370 H2S', '#e1f73b'),
  ('C&R AP Series', 'C&R comunes de analizadores Horiba modelos AP Series', '#ec4899'),
  ('C&R D-R 290', 'C&R de opacímetros Durag DR-290', '#d946ef'),
  ('C&R EDM 180', 'C&R de monitores de PM Grimm EDM180', '#b88414'),
  ('C&R ENDA Series', 'C&R de analizadores Horiba ENDA Series', '#facc15'),
  ('C&R Enviro', 'C&R de monitores Grimm Enviro', '#4ade80'),
  ('C&R OCMA-500', 'C&R de analizadores Horiba OCMA-500', '#f472b6'),
  ('C&R PG Series', 'C&R de analizadores Horiba PG Series', '#2dd4bf'),
  ('C&R Series 6103', 'C&R de calibradores Environics Series 6103', '#a78bfa'),
  ('C&R Series 7000', 'C&R de generadores de aire cero Environics Series 7000', '#fb923c'),
  ('C&R Shelter', 'C&R de Shelters', '#22c55e'),
  ('C&R TCA CTS-01S', 'C&R de Convertidores TCA CTS-01S', '#993bf7'),
  ('C&R U-50 Series', 'C&R de analizadores Horiba U-50 Series', '#3b82f6'),
  ('D-ESI 100', 'Sistema D-ESI 100 para opacímetros Durag', '#f97316'),
  ('D-R 290', 'Opacímetros Durag D-R 290', '#6366f1'),
  ('D-TB 100', 'Sistema D-TB 100 para opacímetros Durag', '#d946ef'),
  ('Durag', 'Otros productos o servicios Durag', '#14b8a6'),
  ('EDM180 Series', 'Monitores de PM Grimm modelo EDM180', '#facc15'),
  ('EDM 280 Series', 'Monitores de PM Grimm modelo EDM 280', '#f59e0b'),
  ('Electrodos LAQUA', 'Electrodos Horiba modelo LAQUA', '#8b5cf6'),
  ('Intereses', 'Intereses de financiación', '#ef4444'),
  ('Kunak Air Series', 'Analizadores Kunak modelos Kunak Air Series', '#10b981'),
  ('LAQUAtwin', 'Analizadores Horiba modelos LAQUAtwin Series', '#3b82f6'),
  ('LAQUA WQ-300', 'Analizadores Horiba modelo WQ-300', '#06b6d4'),
  ('Meteorología', 'Estaciones o sensores meteorológicos', '#84cc16'),
  ('Obra Civil', 'Servicios de Obra Civil', '#f97316'),
  ('OCMA-500 Series', 'Analizadores Horiba modelo OCMA-500 Series', '#6366f1'),
  ('Opcional AP Series', 'Opcional de Analizadores Horiba modelos AP Series', '#d946ef'),
  ('Opcional EDM180', 'Opcional de Monitores de PM Grimm modelo EDM180', '#14b8a6'),
  ('Opcional Nano', 'Opcional de Monitores de PM Grimm Nano Series', '#facc15'),
  ('Opcional OCMA-500', 'Opcional Analizadores Horiba modelo OCMA-500 Series', '#ec4899'),
  ('Opcional Series 7000', 'Opcional Calibradores Environics modelo Series 7000', '#a855f7'),
  ('Opcional WQ-300', 'Opcional de Sensores de Calidad del Agua Horiba WQ-300', '#ea3bf7'),
  ('Operación de Redes', 'Operación y Mantenimiento de Redes de Monitoreo de Calidad del Aire', '#0284c7'),
  ('Series 6100', 'Calibradores Environics Series 6100', '#ea580c'),
  ('Series 7000', 'Generadores de Aire Cero Environics Series 7000', '#16a34a'),
  ('Shelter', 'Shelters y cabinas', '#4f46e5'),
  ('Soluciones LAQUA', 'Soluciones Horiba LAQUA', '#3B82F6'),
  ('Soluciones U-50 Series', 'Soluciones de calibración de Sonda Multiparamétrica Horiba U-50 Series', '#3bf761'),
  ('ST', 'Servicio Técnico General', '#c026d3'),
  ('ST APMA', 'Servicio Técnico Analizador Horiba APMA', '#0891b2'),
  ('ST APNA', 'Servicio Técnico Analizador Horiba APNA', '#65a30d'),
  ('ST APOA', 'Servicio Técnico Analizador Horiba APOA', '#e11d48'),
  ('ST APSA', 'Servicio Técnico Analizador Horiba APSA', '#2563eb'),
  ('ST EDM 180', 'Servicio Técnico Monitor de PM Grimm EDM180', '#9333ea'),
  ('SW&HW', 'Software y Hardware', '#db2777'),
  ('Traducción', 'Servicios de Traducción', '#d97706'),
  ('Transportes', 'Transporte de equipos o C&R', '#059669'),
  ('U-50 Series', 'Analizadores Horiba modelo U-50 Series', '#7c3aed'),
  ('VA Series', 'Analizadores Horiba modelo VA Series', '#ca8a04')
ON CONFLICT (name) DO UPDATE
  SET description = EXCLUDED.description, color = EXCLUDED.color
  WHERE c.description IS NULL;
